# Generated by Django 3.1.3 on 2022-01-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_accuracysc'),
    ]

    operations = [
        migrations.CreateModel(
            name='accuracycnn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracyv', models.FloatField(max_length=1000)),
                ('accuracyloss', models.FloatField(max_length=1000)),
            ],
        ),
    ]
